export const REQUEST_MOVIES = 'REQUEST_MOVIES'

export const TOGGLE_FORM = 'TOGGLE_FORM'

export const GET_RANDOM_MOVIE_SUCCESS = 'GET_RANDOM_MOVIE_SUCCESS'
export const GET_RANDOM_MOVIE_FAILURE = 'GET_RANDOM_MOVIE_FAILURE'

export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS'
export const SEARCH_MOVIE_FAILURE = 'SEARCH_MOVIE_FAILURE'

export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS'
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE'

export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS"
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE"

export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS'
export const GET_ALL_MOVIES_FAILURE = 'GET_ALL_MOVIES_FAILURE'

export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS'
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE'

export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS'
export const POST_MOVIE_FAILURE = 'POST_MOVIE_FAILURE'